### ISSUE TITLE
error in target repeats

### ISSUE THREAD

**Issue by yafei2020** [justlab/casecrossover_preterm_simulation#2]
> library(targets)
> tar_make()
• start target repeats
x error target repeats
• end pipeline
Error : _store_ there is no package called ‘qs’
Error: callr subprocess failed: _store_ there is no package called ‘qs’
Visit https://books.ropensci.org/targets/debugging.html for debugging advice.
Run `rlang::last_error()` to see where the error occurred.

**Comment by yafei2020** [comment]
> tar_make_future(workers = 4L)
• start target repeats
• start target Annual_Singleton_Births_file
• start target LaGuardiaTemp_file
• start target NYBirths_by_Month_plural_file
x error target repeats
• end pipeline
Error : _store_ there is no package called ‘qs’
Error: callr subprocess failed: _store_ there is no package called ‘qs’
Visit https://books.ropensci.org/targets/debugging.html for debugging advice.
Run `rlang::last_error()` to see where the error occurred.

**Comment by dcarrion22** [comment]
Thanks for reporting this issue! We've added `qs` to the list of packages that should be installed in the readme in commit 43ac55ca4577c5c7dcd2221948138adc2baa1ba5. 

If you run `install.packages('qs')`, does that fix the error for you?
